### ISSUE TITLE
IE11 not able to display generated doc

### ISSUE THREAD

**Issue by GuiF73** [twskj/pretty-swag#36] opened 2017-07-18 16:07 UTC
Hi ! 

It seems IE11 is not able to display the generated document.

I have a Active X script warning asking me to actived blocked content, but even if I activate blocked script, the page is always white...

Active X warning is always a pain too :/

**Comment by twskj** [comment] 2017-07-18 18:38
I think it doesn't like embedded css and js. Can you try with switch `-f lite` ?

**Comment by twskj** [comment] 2017-07-18 18:41
I'll find a root cause but for now seems like non-embedded mode works.

![image](https://user-images.githubusercontent.com/25628219/28333722-681245e6-6bbe-11e7-804c-e42163b95d5b.png)

**Comment by GuiF73** [comment] 2017-07-19 07:27
I tried with `-f lite`, it works after I accepted Active X scripts and contents...

**Comment by twskj** [comment] 2017-07-30 06:40
I adjusted the generated html a bit. It works on a few IEs I tested.
Can you help me check on your side please? Just to be clear, there's no active X in my code.
And not sure how to get rid of those warnings

**Comment by twskj** [comment] 2017-08-04 03:45
any feed back on this?

**Comment by GuiF73** [comment] 2017-08-04 21:04
Not sure I can help you more because it was at work and I changed topic right now, and I'm on Mac at home... I think it's IE security policy issue, I was surprised to have ActiveX or script activation request too...

**Comment by twskj** [comment] 2017-08-05 04:33
It's definitely IE thing. So I'll close it for now. Feel free to re-open if you still seeing the problem after after clicking on `accept`

**Closed as completed by twskj** 2017-08-05 04:33 UTC
